### ISSUE TITLE
Uso de versões em pacotes

### ISSUE THREAD

**Issue by benilton** [mgborges/mahalanobisDist#1]
A definição de versões em pacotes segue a regra:

```
x.y.z
```

`x` será zero enquanto o pacote não for oficialmente lançado, etc..
`y` será ímpar para versões de desenvolvimento e par apenas para versões estáveis.
`z` será incrementado em 1 unidade imediatamente antes de fazer um `git push`

A versão atual a ser utilizada deve ser `0.99.1` e a qualquer modificação vc mudará o último dígito (`0.99.2, 0.99.3, ... 0.99.1000`).

**Comment by mgborges** [comment]
versão modificada para 0.99.2
