### ISSUE TITLE
Problema conceitual em permutationPvalue.Rd

### ISSUE THREAD

**Issue by benilton** [mgborges/mahalanobisDist#9]
No documento `permutationPvalue.Rd`, você descreve:

```
The p-values are calculated as the ratio of the random distances higher than the real distance.
```

Os p-valores, conforme minha explicação pessoal e também no texto do manuscrito, são determinados pela proporção de observações sob a hipótese nula de magnitude maior que a estatística observada.

**Comment by mgborges** [comment]
modificado para `p-values determined by the observation proportion on the null hypothesys of been higher than the observed distance.`

**Comment by benilton** [comment]
"We determine the p-value as the proportion of observations, under the null hypothesis, that are at least as extreme as the observed statistic."

**Comment by mgborges** [comment]
Modificado
